// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IqEGaRR3pbbDjAI70hsk1Lfn9Dslr4o',
    appId: '1:714779797129:web:922b3882ffbf2b3b4cc858',
    messagingSenderId: '714779797129',
    projectId: 'mochat-backend',
    authDomain: 'mochat-backend.firebaseapp.com',
    storageBucket: 'mochat-backend.appspot.com',
    measurementId: 'G-516MGWVCXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-moOwECCwNISzov13HeYGO1AlbqjaNOY',
    appId: '1:714779797129:android:fe05b95ef4de28074cc858',
    messagingSenderId: '714779797129',
    projectId: 'mochat-backend',
    storageBucket: 'mochat-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq7RYj-11NxRw7WxTS-scwmMV63iJH-6s',
    appId: '1:714779797129:ios:58c1503648ea530e4cc858',
    messagingSenderId: '714779797129',
    projectId: 'mochat-backend',
    storageBucket: 'mochat-backend.appspot.com',
    iosBundleId: 'com.example.miniCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq7RYj-11NxRw7WxTS-scwmMV63iJH-6s',
    appId: '1:714779797129:ios:58c1503648ea530e4cc858',
    messagingSenderId: '714779797129',
    projectId: 'mochat-backend',
    storageBucket: 'mochat-backend.appspot.com',
    iosBundleId: 'com.example.miniCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_IqEGaRR3pbbDjAI70hsk1Lfn9Dslr4o',
    appId: '1:714779797129:web:7ceaece0bbe5ff284cc858',
    messagingSenderId: '714779797129',
    projectId: 'mochat-backend',
    authDomain: 'mochat-backend.firebaseapp.com',
    storageBucket: 'mochat-backend.appspot.com',
    measurementId: 'G-7WGPJ467L5',
  );
}
